<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $karyawans = [
            [
                'kode_karyawan' => 'KAR0001',
                'password' => 'password123',
                'nik_ktp' => '3204019999990001',
                'nama_karyawan' => 'Bambang Suparjo',
                'umur' => 35,
                'email' => 'bambang.suparjo@example.com',
                'no_hp' => '081298765432',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1989-05-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Administrasi No. 10, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'O',
                'jabatan' => 'Staf Administrasi',
                'kat_unit_kerja_id' => 1, 
                'tanggal_mulai_kerja' => '2020-01-15',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'S1 Ekonomi',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0002',
                'password' => 'password123',
                'nik_ktp' => '3204018888880002',
                'nama_karyawan' => 'Siti Aminah',
                'umur' => 28,
                'email' => 'siti.aminah@example.com',
                'no_hp' => '087712345678',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1996-08-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Akademik No. 5, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'A',
                'jabatan' => 'Staf Akademik',
                'kat_unit_kerja_id' => 2, 
                'tanggal_mulai_kerja' => '2021-02-20',
                'ikatan_kerja' => 'Kontrak',
                'pendidikan_tertinggi' => 'D3 Administrasi',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0003',
                'password' => 'password123',
                'nik_ktp' => '3204017777770003',
                'nama_karyawan' => 'Agus Wijoyo',
                'umur' => 42,
                'email' => 'agus.wijoyo@example.com',
                'no_hp' => '085687654321',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1982-11-30',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Teknologi No. 15, Palembang',
                'agama' => 'Kristen',
                'golongan_darah' => 'B',
                'jabatan' => 'Kepala Teknisi IT',
                'kat_unit_kerja_id' => 3, 
                'tanggal_mulai_kerja' => '2018-05-01',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'S1 Teknik Informatika',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0004',
                'password' => 'password123',
                'nik_ktp' => '3204016666660004',
                'nama_karyawan' => 'Dewi Lestari',
                'umur' => 31,
                'email' => 'dewi.lestari@example.com',
                'no_hp' => '081324567890',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1993-03-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pustaka No. 8, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'AB',
                'jabatan' => 'Pustakawan',
                'kat_unit_kerja_id' => 4, 
                'tanggal_mulai_kerja' => '2019-07-10',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'S1 Ilmu Perpustakaan',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0005',
                'password' => 'password123',
                'nik_ktp' => '3204015555550005',
                'nama_karyawan' => 'Eko Prasetyo',
                'umur' => 29,
                'email' => 'eko.prasetyo@example.com',
                'no_hp' => '089876543210',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1995-01-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Keuangan No. 20, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'O',
                'jabatan' => 'Staf Keuangan',
                'kat_unit_kerja_id' => 1, 
                'tanggal_mulai_kerja' => '2022-03-01',
                'ikatan_kerja' => 'Kontrak',
                'pendidikan_tertinggi' => 'D3 Akuntansi',
                'status_aktivasi' => 'tidak_aktif',
            ],
            [
                'kode_karyawan' => 'KAR0006',
                'password' => 'password123',
                'nik_ktp' => '3204014444440006',
                'nama_karyawan' => 'Rina Hartati',
                'umur' => 38,
                'email' => 'rina.hartati@example.com',
                'no_hp' => '082187654321',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-09-18',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Humas No. 1, Palembang',
                'agama' => 'Katolik',
                'golongan_darah' => 'A',
                'jabatan' => 'Kepala Humas',
                'kat_unit_kerja_id' => 5, 
                'tanggal_mulai_kerja' => '2015-11-05',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'S1 Ilmu Komunikasi',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0007',
                'password' => 'password123',
                'nik_ktp' => '3204013333330007',
                'nama_karyawan' => 'Hendro Siswanto',
                'umur' => 25,
                'email' => 'hendro.siswanto@example.com',
                'no_hp' => '087812349876',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1999-07-22',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Sarana No. 3, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'B',
                'jabatan' => 'Staf Sarana & Prasarana',
                'kat_unit_kerja_id' => 6, 
                'tanggal_mulai_kerja' => '2023-01-30',
                'ikatan_kerja' => 'Kontrak',
                'pendidikan_tertinggi' => 'SMK Bangunan',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0008',
                'password' => 'password123',
                'nik_ktp' => '3204012222220008',
                'nama_karyawan' => 'Fitriani',
                'umur' => 27,
                'email' => 'fitriani@example.com',
                'no_hp' => '081234567891',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1997-12-01',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Layanan Mahasiswa No. 12, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'O',
                'jabatan' => 'Staf Kemahasiswaan',
                'kat_unit_kerja_id' => 2, 
                'tanggal_mulai_kerja' => '2022-08-15',
                'ikatan_kerja' => 'Kontrak',
                'pendidikan_tertinggi' => 'S1 Psikologi',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0009',
                'password' => 'password123',
                'nik_ktp' => '3204011111110009',
                'nama_karyawan' => 'Iwan Setiawan',
                'umur' => 33,
                'email' => 'iwan.setiawan@example.com',
                'no_hp' => '085789012345',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '1991-04-14',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Jaringan No. 7, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'A',
                'jabatan' => 'Teknisi Jaringan',
                'kat_unit_kerja_id' => 3, 
                'tanggal_mulai_kerja' => '2020-09-01',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'D3 Teknik Komputer',
                'status_aktivasi' => 'aktif',
            ],
            [
                'kode_karyawan' => 'KAR0010',
                'password' => 'password123',
                'nik_ktp' => '3204010000000010',
                'nama_karyawan' => 'Lina Marlina',
                'umur' => 45,
                'email' => 'lina.marlina@example.com',
                'no_hp' => '081122334455',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1979-02-28',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Kebersihan No. 2, Palembang',
                'agama' => 'Islam',
                'golongan_darah' => 'B',
                'jabatan' => 'Petugas Kebersihan',
                'kat_unit_kerja_id' => 6, 
                'tanggal_mulai_kerja' => '2010-03-10',
                'ikatan_kerja' => 'Tetap',
                'pendidikan_tertinggi' => 'SMP',
                'status_aktivasi' => 'tidak_aktif',
            ],
        ];

        foreach ($karyawans as $karyawanData) {
            $user = null;
            if ($karyawanData['status_aktivasi'] === 'aktif') {
                $user = User::create([
                    'name' => $karyawanData['nama_karyawan'],
                    'email' => $karyawanData['email'],
                    'kode' => $karyawanData['kode_karyawan'],
                    'password' => Hash::make($karyawanData['password']),
                ]);
                $user->assignRole('karyawan');
            }

            Karyawan::create([
                'user_id' => $user?->id,
                'kode_karyawan' => $karyawanData['kode_karyawan'],
                'password' => Hash::make($karyawanData['password']),
                'nik_ktp' => $karyawanData['nik_ktp'],
                'nama_karyawan' => $karyawanData['nama_karyawan'],
                'email' => $karyawanData['email'],
                'umur' => $karyawanData['umur'],
                'tempat_lahir' => $karyawanData['tempat_lahir'],
                'tanggal_lahir' => $karyawanData['tanggal_lahir'],
                'alamat' => $karyawanData['alamat'],
                'agama' => $karyawanData['agama'],
                'jenis_kelamin' => $karyawanData['jenis_kelamin'],
                'no_hp' => $karyawanData['no_hp'],
                'pendidikan_tertinggi' => $karyawanData['pendidikan_tertinggi'],
                'ikatan_kerja' => $karyawanData['ikatan_kerja'],
                'jabatan' => $karyawanData['jabatan'],
                'tanggal_mulai_kerja' => $karyawanData['tanggal_mulai_kerja'],
                'kat_unit_kerja_id' => $karyawanData['kat_unit_kerja_id'],
                'status_aktivasi' => $karyawanData['status_aktivasi'],
            ]);
        }
    }
}
